//
//  State.swift
//  NPS
//
//  Created by Mindy Douglas on 6/4/23.
//

import Foundation

struct State {
    var name: String
    var abbreviation: String
}

extension State {
    static func loadStateData() -> [State] {
        return [
            State(name: "Alabama",
                  abbreviation: "AL"),
            State(name: "Alaska",
                  abbreviation: "AK"),
            State(name: "Arizona",
                  abbreviation: "AZ"),
            State(name: "Arkansas",
                  abbreviation: "AR"),
            State(name: "California",
                  abbreviation: "CA"),
            State(name: "Colorado",
                  abbreviation: "CO"),
            State(name: "Connecticut",
                  abbreviation: "CT"),
            State(name: "Delaware",
                  abbreviation: "DE"),
            State(name: "Florida",
                  abbreviation: "FL"),
            State(name: "Georgia",
                  abbreviation: "GA"),
            State(name: "Hawaii",
                  abbreviation: "HI"),
            State(name: "Idaho",
                  abbreviation: "ID"),
            State(name: "Illinois",
                  abbreviation: "IL"),
            State(name: "Indiana",
                  abbreviation: "IN"),
            State(name: "Iowa",
                  abbreviation: "IA"),
            State(name: "Kansas",
                  abbreviation: "KS"),
            State(name: "Kentucky",
                  abbreviation: "KY"),
            State(name: "Louisana",
                  abbreviation: "LA"),
            State(name: "Maine",
                  abbreviation: "ME"),
            State(name: "Maryland",
                  abbreviation: "MD"),
            State(name: "Massachusetts",
                 abbreviation: "MA"),
            State(name: "Michigan",
                  abbreviation: "MI"),
            State(name: "Minnesota",
                  abbreviation: "MN"),
            State(name: "Mississippi",
                  abbreviation: "MS"),
            State(name: "Missouri",
                  abbreviation: "MO"),
            State(name: "Montana",
                  abbreviation: "MT"),
            State(name: "Nebraska",
                  abbreviation: "NE"),
            State(name: "Nevada",
                  abbreviation: "NV"),
            State(name: "New Hampshire",
                  abbreviation: "NH"),
            State(name: "New Jersey",
                  abbreviation: "NJ"),
            State(name: "New Mexico",
                  abbreviation: "NM"),
            State(name: "New York",
                  abbreviation: "NY"),
            State(name: "North Carolina",
                  abbreviation: "NC"),
            State(name: "North Dakota",
                  abbreviation: "ND"),
            State(name: "Ohio",
                  abbreviation: "OH"),
            State(name: "Oklahoma",
                  abbreviation: "OK"),
            State(name: "Oregon",
                  abbreviation: "OR"),
            State(name: "Pennsylvania",
                  abbreviation: "PA"),
            State(name: "Rhode Island",
                  abbreviation: "RI"),
            State(name: "South Carolina",
                  abbreviation: "SC"),
            State(name: "South Dakota",
                  abbreviation: "SD"),
            State(name: "Tenessee",
                  abbreviation: "TN"),
            State(name: "Texas",
                  abbreviation: "TX"),
            State(name: "Utah",
                  abbreviation: "UT"),
            State(name: "Vermont",
                  abbreviation: "VT"),
            State(name: "Virginia",
                  abbreviation: "VA"),
            State(name: "Washington",
                  abbreviation: "WA"),
            State(name: "West Virginia",
                  abbreviation: "WV"),
            State(name: "Wisconsin",
                  abbreviation: "WI"),
            State(name: "Wyoming",
                  abbreviation: "WY")
        ]
    }
}
